<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-25T04:45:59Z" name="BDD Test Suite" finished-at="2023-05-25T04:46:38Z" duration-ms="39277">
    <groups>
      <group name="cucumber">
        <method signature="TestRunner.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:MyRunner.TestRunner@6b1274d2]" name="feature" class="MyRunner.TestRunner"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-05-25T04:45:59Z" name="Guru99 Bank Test" finished-at="2023-05-25T04:46:38Z" duration-ms="39277">
      <class name="MyRunner.TestRunner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:MyRunner.TestRunner@6b1274d2]" started-at="2023-05-25T04:45:59Z" name="setUpClass" finished-at="2023-05-25T04:45:59Z" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:MyRunner.TestRunner@6b1274d2]" started-at="2023-05-25T04:45:59Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2023-05-25T04:46:37Z" duration-ms="37431" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Guru99 Login Feature]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [] but found [Guru99 Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [] but found [Guru99 Bank Home Page]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at MyRunner.TestRunner.feature(TestRunner.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.AssertionError: expected [] but found [Guru99 Bank Home Page]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at stepDefinitions.LogInPageStepDefinition.user_is_on_Home_Page(LogInPageStepDefinition.java:61)
at âœ½.Then user is on Home Page(login.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:MyRunner.TestRunner@6b1274d2]" started-at="2023-05-25T04:46:37Z" name="tearDownClass" finished-at="2023-05-25T04:46:38Z" duration-ms="1033" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- MyRunner.TestRunner -->
    </test> <!-- Guru99 Bank Test -->
  </suite> <!-- BDD Test Suite -->
</testng-results>
